// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	Active    BookingStatus = "active"
	Cancelled BookingStatus = "cancelled"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Cancelled:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	BOOKINGNOTFOUND   ErrorResponseErrorCode = "BOOKING_NOT_FOUND"
	FORBIDDEN         ErrorResponseErrorCode = "FORBIDDEN"
	INTERNALERROR     ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDREQUEST    ErrorResponseErrorCode = "INVALID_REQUEST"
	NOTFOUND          ErrorResponseErrorCode = "NOT_FOUND"
	ROOMNOTFOUND      ErrorResponseErrorCode = "ROOM_NOT_FOUND"
	SCHEDULEEXISTS    ErrorResponseErrorCode = "SCHEDULE_EXISTS"
	SLOTALREADYBOOKED ErrorResponseErrorCode = "SLOT_ALREADY_BOOKED"
	SLOTNOTFOUND      ErrorResponseErrorCode = "SLOT_NOT_FOUND"
	UNAUTHORIZED      ErrorResponseErrorCode = "UNAUTHORIZED"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case BOOKINGNOTFOUND:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case INVALIDREQUEST:
		return true
	case NOTFOUND:
		return true
	case ROOMNOTFOUND:
		return true
	case SCHEDULEEXISTS:
		return true
	case SLOTALREADYBOOKED:
		return true
	case SLOTNOTFOUND:
		return true
	case UNAUTHORIZED:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PostDummyLoginJSONBodyRole.
const (
	PostDummyLoginJSONBodyRoleAdmin PostDummyLoginJSONBodyRole = "admin"
	PostDummyLoginJSONBodyRoleUser  PostDummyLoginJSONBodyRole = "user"
)

// Valid indicates whether the value is a known member of the PostDummyLoginJSONBodyRole enum.
func (e PostDummyLoginJSONBodyRole) Valid() bool {
	switch e {
	case PostDummyLoginJSONBodyRoleAdmin:
		return true
	case PostDummyLoginJSONBodyRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PostRegisterJSONBodyRole.
const (
	PostRegisterJSONBodyRoleAdmin PostRegisterJSONBodyRole = "admin"
	PostRegisterJSONBodyRoleUser  PostRegisterJSONBodyRole = "user"
)

// Valid indicates whether the value is a known member of the PostRegisterJSONBodyRole enum.
func (e PostRegisterJSONBodyRole) Valid() bool {
	switch e {
	case PostRegisterJSONBodyRoleAdmin:
		return true
	case PostRegisterJSONBodyRoleUser:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking struct {
	ConferenceLink *string            `json:"conferenceLink,omitempty"`
	CreatedAt      *time.Time         `json:"createdAt,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	SlotId         openapi_types.UUID `json:"slotId"`
	Status         BookingStatus      `json:"status"`
	UserId         openapi_types.UUID `json:"userId"`
}

// BookingStatus defines model for Booking.Status.
type BookingStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// InternalErrorResponse defines model for InternalErrorResponse.
type InternalErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page Текущая страница (начиная с 1)
	Page int `json:"page"`

	// PageSize Размер страницы
	PageSize int `json:"pageSize"`

	// Total Общее количество записей
	Total int `json:"total"`
}

// Room defines model for Room.
type Room struct {
	Capacity    *int               `json:"capacity,omitempty"`
	CreatedAt   *time.Time         `json:"createdAt,omitempty"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// DaysOfWeek 1=Пн .. 7=Вс, дни доступности. Каждое значение должно быть в диапазоне 1–7.
	DaysOfWeek []int `json:"daysOfWeek"`

	// EndTime Время окончания (HH:MM) в рамках дня. Интерпретируется как UTC.
	EndTime string              `json:"endTime"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	RoomId  openapi_types.UUID  `json:"roomId"`

	// StartTime Время начала (HH:MM) в рамках дня. Интерпретируется как UTC.
	StartTime string `json:"startTime"`
}

// Slot defines model for Slot.
type Slot struct {
	// End Время окончания слота в UTC (ISO 8601, например 2024-06-10T09:30:00Z)
	End    time.Time          `json:"end"`
	Id     openapi_types.UUID `json:"id"`
	RoomId openapi_types.UUID `json:"roomId"`

	// Start Время начала слота в UTC (ISO 8601, например 2024-06-10T09:00:00Z)
	Start time.Time `json:"start"`
}

// Token defines model for Token.
type Token struct {
	// Token JWT для заголовка Authorization Bearer
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Role      UserRole            `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// BookingIdPath defines model for BookingIdPath.
type BookingIdPath = openapi_types.UUID

// RoomIdPath defines model for RoomIdPath.
type RoomIdPath = openapi_types.UUID

// PostBookingsCreateJSONBody defines parameters for PostBookingsCreate.
type PostBookingsCreateJSONBody struct {
	CreateConferenceLink *bool              `json:"createConferenceLink,omitempty"`
	SlotId               openapi_types.UUID `json:"slotId"`
}

// GetBookingsListParams defines parameters for GetBookingsList.
type GetBookingsListParams struct {
	// Page Номер страницы (начиная с 1). По умолчанию 1.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Количество записей на странице. По умолчанию 20, максимум 100.
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostDummyLoginJSONBody defines parameters for PostDummyLogin.
type PostDummyLoginJSONBody struct {
	Role PostDummyLoginJSONBodyRole `json:"role"`
}

// PostDummyLoginJSONBodyRole defines parameters for PostDummyLogin.
type PostDummyLoginJSONBodyRole string

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Email    openapi_types.Email      `json:"email"`
	Password string                   `json:"password"`
	Role     PostRegisterJSONBodyRole `json:"role"`
}

// PostRegisterJSONBodyRole defines parameters for PostRegister.
type PostRegisterJSONBodyRole string

// PostRoomsCreateJSONBody defines parameters for PostRoomsCreate.
type PostRoomsCreateJSONBody struct {
	Capacity    *int    `json:"capacity,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// GetRoomsRoomIdSlotsListParams defines parameters for GetRoomsRoomIdSlotsList.
type GetRoomsRoomIdSlotsListParams struct {
	// Date Дата в формате ISO 8601 (например: 2024-06-10). Обязательный параметр; при отсутствии — 400.
	Date openapi_types.Date `form:"date" json:"date"`
}

// PostBookingsCreateJSONRequestBody defines body for PostBookingsCreate for application/json ContentType.
type PostBookingsCreateJSONRequestBody PostBookingsCreateJSONBody

// PostDummyLoginJSONRequestBody defines body for PostDummyLogin for application/json ContentType.
type PostDummyLoginJSONRequestBody PostDummyLoginJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// PostRoomsCreateJSONRequestBody defines body for PostRoomsCreate for application/json ContentType.
type PostRoomsCreateJSONRequestBody PostRoomsCreateJSONBody

// PostRoomsRoomIdScheduleCreateJSONRequestBody defines body for PostRoomsRoomIdScheduleCreate for application/json ContentType.
type PostRoomsRoomIdScheduleCreateJSONRequestBody = Schedule

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать бронь на слот (только user). Опционально — запросить ссылку на конференцию.
	// (POST /bookings/create)
	PostBookingsCreate(w http.ResponseWriter, r *http.Request)
	// Список всех броней с пагинацией (только admin)
	// (GET /bookings/list)
	GetBookingsList(w http.ResponseWriter, r *http.Request, params GetBookingsListParams)
	// Список броней текущего пользователя (только user)
	// (GET /bookings/my)
	GetBookingsMy(w http.ResponseWriter, r *http.Request)
	// Отменить бронь (только своя бронь, только user)
	// (POST /bookings/{bookingId}/cancel)
	PostBookingsBookingIdCancel(w http.ResponseWriter, r *http.Request, bookingId BookingIdPath)
	// Получить тестовый JWT по роли (ОБЯЗАТЕЛЬНО). Доступен без авторизации.
	// (POST /dummyLogin)
	PostDummyLogin(w http.ResponseWriter, r *http.Request)
	// Авторизация по email и паролю (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /login)
	PostLogin(w http.ResponseWriter, r *http.Request)
	// Регистрация пользователя (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /register)
	PostRegister(w http.ResponseWriter, r *http.Request)
	// Создать переговорку (только admin)
	// (POST /rooms/create)
	PostRoomsCreate(w http.ResponseWriter, r *http.Request)
	// Список переговорок (admin и user)
	// (GET /rooms/list)
	GetRoomsList(w http.ResponseWriter, r *http.Request)
	// Создать расписание переговорки (только admin, только один раз). Длительность слота 30 мин. После создания расписание изменить нельзя.
	// (POST /rooms/{roomId}/schedule/create)
	PostRoomsRoomIdScheduleCreate(w http.ResponseWriter, r *http.Request, roomId RoomIdPath)
	// Список доступных для бронирования слотов по переговорке и дате (admin и user). Наиболее нагруженный эндпоинт.
	// (GET /rooms/{roomId}/slots/list)
	GetRoomsRoomIdSlotsList(w http.ResponseWriter, r *http.Request, roomId RoomIdPath, params GetRoomsRoomIdSlotsListParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Создать бронь на слот (только user). Опционально — запросить ссылку на конференцию.
// (POST /bookings/create)
func (_ Unimplemented) PostBookingsCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список всех броней с пагинацией (только admin)
// (GET /bookings/list)
func (_ Unimplemented) GetBookingsList(w http.ResponseWriter, r *http.Request, params GetBookingsListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список броней текущего пользователя (только user)
// (GET /bookings/my)
func (_ Unimplemented) GetBookingsMy(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Отменить бронь (только своя бронь, только user)
// (POST /bookings/{bookingId}/cancel)
func (_ Unimplemented) PostBookingsBookingIdCancel(w http.ResponseWriter, r *http.Request, bookingId BookingIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить тестовый JWT по роли (ОБЯЗАТЕЛЬНО). Доступен без авторизации.
// (POST /dummyLogin)
func (_ Unimplemented) PostDummyLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Авторизация по email и паролю (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
// (POST /login)
func (_ Unimplemented) PostLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация пользователя (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
// (POST /register)
func (_ Unimplemented) PostRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать переговорку (только admin)
// (POST /rooms/create)
func (_ Unimplemented) PostRoomsCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список переговорок (admin и user)
// (GET /rooms/list)
func (_ Unimplemented) GetRoomsList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать расписание переговорки (только admin, только один раз). Длительность слота 30 мин. После создания расписание изменить нельзя.
// (POST /rooms/{roomId}/schedule/create)
func (_ Unimplemented) PostRoomsRoomIdScheduleCreate(w http.ResponseWriter, r *http.Request, roomId RoomIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список доступных для бронирования слотов по переговорке и дате (admin и user). Наиболее нагруженный эндпоинт.
// (GET /rooms/{roomId}/slots/list)
func (_ Unimplemented) GetRoomsRoomIdSlotsList(w http.ResponseWriter, r *http.Request, roomId RoomIdPath, params GetRoomsRoomIdSlotsListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostBookingsCreate operation middleware
func (siw *ServerInterfaceWrapper) PostBookingsCreate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostBookingsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookingsList operation middleware
func (siw *ServerInterfaceWrapper) GetBookingsList(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBookingsListParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookingsList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookingsMy operation middleware
func (siw *ServerInterfaceWrapper) GetBookingsMy(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookingsMy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostBookingsBookingIdCancel operation middleware
func (siw *ServerInterfaceWrapper) PostBookingsBookingIdCancel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", chi.URLParam(r, "bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostBookingsBookingIdCancel(w, r, bookingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDummyLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDummyLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDummyLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRoomsCreate operation middleware
func (siw *ServerInterfaceWrapper) PostRoomsCreate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRoomsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomsList operation middleware
func (siw *ServerInterfaceWrapper) GetRoomsList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRoomsRoomIdScheduleCreate operation middleware
func (siw *ServerInterfaceWrapper) PostRoomsRoomIdScheduleCreate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId RoomIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", chi.URLParam(r, "roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRoomsRoomIdScheduleCreate(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomsRoomIdSlotsList operation middleware
func (siw *ServerInterfaceWrapper) GetRoomsRoomIdSlotsList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId RoomIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", chi.URLParam(r, "roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRoomsRoomIdSlotsListParams

	// ------------- Required query parameter "date" -------------

	if paramValue := r.URL.Query().Get("date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomsRoomIdSlotsList(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings/create", wrapper.PostBookingsCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings/list", wrapper.GetBookingsList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings/my", wrapper.GetBookingsMy)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings/{bookingId}/cancel", wrapper.PostBookingsBookingIdCancel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dummyLogin", wrapper.PostDummyLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.PostLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/register", wrapper.PostRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rooms/create", wrapper.PostRoomsCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rooms/list", wrapper.GetRoomsList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rooms/{roomId}/schedule/create", wrapper.PostRoomsRoomIdScheduleCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rooms/{roomId}/slots/list", wrapper.GetRoomsRoomIdSlotsList)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x863IbR3b/q3TNf6v+IAsCh5J2bcOlSskivaYjiw4vcbJcRhwBLXJWAAY7M9CaZljF",
	"i2XZRVmUFLni2o3lS75mKyBFiOAF0CucfoV9ktQ53XNFAwRFSqEUfZHAuXSfPpffufTpWTIKTrnqVHjF",
	"94z8klG1XKvMfe7SXx84zi27Mj9W/NTyF/BCkXsF1676tlMx8gZ8DzvQgJZYg6b4EpqwD3WxBm2xwmBL",
	"rEAbWtA0soaND1dxiKxRscrcyBs3gpGNrOHyP9ZslxeNvO/WeNbwCgu8bOF0Nx23bPlG3qjVbHzSX6zi",
	"y57v2pV5Y3k5a0w4TvlFyHsODbECDXgKbdjGS7DfjVSXpjgRncvBw3GuErtdp8pd3+Z0o+BUbnKXVwr8",
	"ql25lRzYtZGiWqlk3SjxgILUPFmj4HLL58XLfuLlouXzc75d5v0MYRf7WFHW8EqOP9bno77l12iBvFIr",
	"G/kZwyr49m2kpmBVCrxU4kVjVvNizeNuX3Msx4UzY9AjisBwlJCOaCbnxh94wceZRl3XcSe4V3UqHidK",
	"P7fK1ZL8ifekeIr41ti1f7x8dWzk+sToP0yPTk4ZWaPMPc+ax3t25bZVsosMqeGeT5QlZRyOlhZ9kcc5",
	"1DnJ9LXL01MfjU+M/W50xMga18anrn84Pn0Nf0+Mj39yPX5h8ur4VOeFy1cnRi+P/PP1D8bH/57GwB9j",
	"136bePLD8YkPxkZGRq/hW1c+Gh2Zvjp6ffSfxianJo2sMXZtanTi2uWr10cnJsYntEILmbF0hJRoydHz",
	"nWJJPS85p5PeWMXnbsUqHU+KiZUkhSiHYx53b3OXyVePL8pg8s65zgLTPrXm7YoloTK9hKqiJYWnv0AD",
	"9sW6+AbqYpOJVbEmVqCOIC++gjrLQAvq4i406X98gA0PRKtFts5zF+fG8SftL3Rz/AR12IVDhOfUDGJD",
	"O5bv+FZJM9AT2BLfQAMaDPahDQfQFHehgUMi4DPYhTo8h6ZYhQbsaUZOMZJYEqM8mFjHWnRKGr2wqlbB",
	"9hfxdxcUji3rFJA8wZClU0N+6RaX+sFgelTHocnCAi/WpGUmuVS0Fr3xm59xfqtTpsOX4EdosVyOvXMJ",
	"HonVLIMd1A38r03Ksg7PoSV/QzPH4M9Qh2d4F9VgV+lnA9/BCzukF8/wDQxYNsSauMdgG280STtQFTGI",
	"abDhv6382zs5DBB8XiZCy9bndhnB+p2sUbYr8vewVkPlFct1rUX8m1eKU3ZZp/yPKCY5FJsM2qS1LXFX",
	"qf8my3z0Uf6TTwaQQDKKQ4pn7hAPxGaOwfcU6mBc8xzHobBnRazjL7GKY+5DHfbZ9NSVHGmyjzBn5I1/",
	"ycyYw7N/N2Oee2/2X8/PmOcuzA7kZ8xzv56lS78yXlxXVOzUZ5Tg+kfzRYqwDgcIOGeHIyntD2PGmDrH",
	"lxgpgdY6So7faRm8UjyuyohVOIC2WIM68mh66grLjE2Os3d/Yw5niZXEl6aC2/Pm+YvnzN+cGzanzPfy",
	"F8y8af4O8VuLPq9KI/rXhpMs1jzWYnVQF0pcUk0C1gp3yrnFNS7XDy4nF/vxZ1Oozge4WPRYTwmyMGfZ",
	"hzq7XPMXHNf+gtw4+4BbLnePJFfOpCNt2uO6eObknoiXLbuUeF1eOYkalRLxslUs2xUV7GvCUp3EAhJo",
	"KG0g5fFCzbX9RfRWZckMyWPkO/51g/76MCD2488wUKdMj3LclDwWfL8qk0G7ctPRKPbPBFXbGJTEEmj6",
	"fzu0aU3q2oZ9nMX2KdrE6IOpHJNNcve2XeAsM8U9n01Z3i1U8tvc9ZRLzZk5ExnqVHnFqtpG3riQM3MX",
	"JBwu0JqHVLLuDUlVIBVxPJ1pPk76YYbpNhyIe4hMjCg9gCZDIeUYPIAdOKRosRlEekF6ji4XDqENzxCr",
	"0bTbsAs7UEdGSDcd8odlLpoXBnJsTiZ6cwy2kEPiYQDyTdhlH382dY6I2Sf3X88yhAmaBm+jlyAQkWEh",
	"Di1WoZ5j8B3BSpPBtkQder0FbdgLAUfC0B1oY9wQTLrN1DBfk70esgwBA/t9zTQvFFjF+dNAlqH8YJeG",
	"rmNUHTqmi6bJMqkccCD3e9RwNE2yd0RR41PH85WsvStSOlLVOV4vLqqygs8rJC6rWi3ZBXp96A+ejAuj",
	"MobO7q901CSK/KZVK/lG/qZV8iJrv+E4JW5VjlUbSJmlek9ji8vp6gtdkIkeEXveHD7BUm9EFZlfufym",
	"kTf+31BUFxtStZuhoHCzvKylMGULD6WCintx9W1BHTl00TSPRW4vqpJZr46SH6AB24QaLbEBewkll9QM",
	"v1pqGBqytHU0vwDfJC0XXiEtMbyKuNIQ34iH0GIZPQarzKFPnBuQi7r4Chf1cwRLDRn47MlCqCTlvT5I",
	"6VE40ZeSouoJGjGzPWaVXG4VFxnaFi8aUQ309BYo1tE/SMG1xKZYwwX++hRNS19Y0pH0CFpinXwY+Qex",
	"SQG5+BqasEWhmlhVzh3/rSfCCyM/kwwsZmaXZ7OGVyuXLXdRLljhR8L14c9WLPBlmYQakvblGDyB5+Ir",
	"aJIi1+kuauzfVh4nnV2TxharYlVswAHsi3U5ukoqvlRRRwvHEvcxX/KteQ9hO/A/xiyuKooWSraMEeb5",
	"i4cKFNflGPxI3nWHiHgGTbJFjAwoSX+qSk5EGaMyD5K6S3dVZoiedUVssLmqNc/nGDTlr0n7Cz5HTNrC",
	"taaex0vtTvaJjfdT1QQZl7VRIw9pGUEOdj8v57k0PJeNZrx03sRJ/wOzT2Q9HEaS0VUqIlJJbsOmqYsF",
	"fsvDUOAqsj6b2M2ZWeoE4naXQpu+lCfFoFkjG84FWyd/rHF3Mdo7UVWzyNrC4GG4d9VkOdtB7p+PrOIF",
	"5pCoSza6k33ezDJivRICPkLM7bEaVfzTrOi8mY2KQsOmecQCZzsiGPPkEQz9DktUfcUynfWpaqIy3GuQ",
	"WA25v5joZyWsNuxjRI2YeCcK5Ruwd7aCI7KDBiKSWCFI2Rdr9FhDBy1pLILmwNvoqnt0lQB8wvmBN9d/",
	"H6H2CLAd6oPXtVw62vWWF0/qeFWO/qgzQY2n3uj06F2lZTKPFptZ8sKwJ5Py63ZxTiZBoQOP0uRUZt7o",
	"nFTcV08nKI1TQXHKlliHHdqdQpcZBEXozGKZN79Eqff7Ha8HsWSQtDdgh6SfGAmz+ja5nkYYX2/DPhyI",
	"++hWAkKPcM6fLBpnFPuPj+EJHV4L9wepOtVVO96iYp+oGCaQbzwovpAeabl1NDguhc1Hy0OyAeW0Kpo/",
	"aum8Fy9lEn4cqqyBMq7EgKtU0r0fy/FkBic5TBnOJhschCZl9IfIGZqlhYEJ1AcH85JbgaarmGZbbEii",
	"kmAX0oK6p6qaSWBsMLEJ28jsaNMs0gB6vqktY7LzpkleDaNrZF+YO8Eh+QKK4dtiU6Y4cJio6MpWnTwL",
	"+4Mo+UDLlct7LjbEGnoMDT/v4urEeoKJlDZdNC9Eo7RpNev0LwJ6Ey9GFIhVZNI+7QDXSfmR7rERNdDF",
	"o2qxYefcFalgHbmYzkKjR4aSnXcvJ1l4WeXOmEio1s4y0CQrCdRuiyoM9c4HVdrWgMZrGjn3qJvFG6ui",
	"alnBqlQcX+k5syqOv8BdgpP/77EbMQGc5ioVymwmKklKRCsSjaTt027aK69fPoyXt5IVTFk9fxO94ZMU",
	"jMVEk9G5iLjwsuw4frBYK5cXrzrzdqWH23skNqje+FCskT+WaE1+ZI/FNqWTICm3xQKnmKF0hQ2FlcjH",
	"ch97P2zKiT3cdStscFD27lKJMirDS8c2PT02MjjYNUDIM7kpBy10U2TYa4wwCF8MN9bDjCxeD0VniV5A",
	"GYS4L7Mv8nd9DJoODf6KD+KbW8hMcuh3Y3VM4m8dttAMZR2Qoo57MiFpRjJIbkWgoxJfScsgzGrANmoD",
	"KekWOkFMh3Bpz9V7DdnqjPw+gDpZFa7uK5lBKfeXC0Qs+6Ma0Eqmb6oOLbtngj1cVT+LMr4M8mOASq2u",
	"U6Iy618Vu8S30IIdElsTY5fOKGNwEHklNlEmQRwlvTDKu5kkLmzeonXXke8RelPWdiDuwxbtw2I6J9ap",
	"CtigvpAGiZ123akS22aSxPhQqp7D5oZcPm97PndlCXmohHY0F4QVkg2BSBPZ6g5FLetShnAoa0jpGnKg",
	"NHk2R8o2F8AyMXXufUbc0r4q4xKzW1wyEhn9ae0Pn6wFo1vXRR87vacH/rIXRwf2v6QgL6pQnMkKZUq7",
	"9LsIgXa9bhll5CRlfoXGG+ZOGs/0PJ6ZZeAJPIT/hn+HB/ALfAd/gf+CH+CJdEdRaidRRG4aJWNAZfrx",
	"DS9y4dKZlo7wow/iY8nOw+7pLFFObUlMJjp15X3u61tFcLk5Bj+lgQqR5FviCmbPaaxFLmvQllSImEYh",
	"SBxxpcbtBNvfCMGRN9dyq7MlUwPmMgC4C3WptowQOOSNWIc9fJbNxSKWuWOLrQseni4UHqO/rWp53p8c",
	"t3h0B3UwRPjG2UXL/1QRzddqu1Ani/+lsl8MORsMoQND2sCJ7oShZOO1xcQHOlb3gBKWgcfwBH6EJ/AX",
	"+AG+j6MifMcIKB/DA7r1nWwTQA+jtd8BPSgGMVIPXIw6Gh7KSjr1Mvau9nWrNAVVwpg036LiC6HiRCC4",
	"swWMJ2337UDS7EnCz5M0GtZUh3Uv5KAu7P5qbt3qzfGGwzMWr6qERkLT697AFaHwTwRCUR9zhML6jYuX",
	"j8GOU9Y1bGuMHp887d7hY511O+5Btf5OoHU5fPayTdxVh/96qSUdEOzXxDsPqtffdhS/tru7QWUuDDLC",
	"ivub3gKTaGHVfH9BrB/V7UJIlcC3VItpR8sFvaGaIU9xA40m77vdQlr7yXst9Ad/zpi1vfGdClopBHsd",
	"YdN/L6VdkmcFl2mdxVqJn9a5qqBZ+idMHhTN4ZEF2YLQkjtIcVtM1qmDrQ3KU3bDLZL4no3+4ylB+wPm",
	"JtGp17nkKWvdLkJHI3VbrLFheo+9wzLy0HdWHflO9AFIKnbk2+l65x4mi9TAECV9HQe76z2PYHVNk1CM",
	"8sszwUH2MH463jZ/7PM1co//xYKvXkYUHrV/6ZGPFzvU3ydF/WCgTpupgeRO2C7QgvaZK8tvM7GWE3dz",
	"TFeg1+/hRGbztnH4xEHUq+1Z0IfpXfoXTn4Gq+PDPLHzV8q62E3HZf6C7TF0N+FxLP657fkesypFpnpP",
	"bnBWWLAq86d8SEvrhHaCfQ6NAwmqAYncpp2lA7qxLqGmZGkjtqVK3kmpwv+N+Jm8VQd39WzVBNXZnk5f",
	"tWrE651hO0LsIwsXTLX1Lz0/3UlJT+1pa0iNZKraXVpqql2xGd9qC3xFtwiq5PhHHTTTtbBHPd1ZpUxh",
	"CUpCM3UtUn9GsitS3KPNuK7NL11kEHRdxhsKqUNRCnQ9xzC4UVsSstU8OnIet5idWDu8ph4e3aMvYJBk",
	"EsdUMDbz+Zyuq1PfbfF+0IESVNm1jZO9gqjoDL1Y78Gfhuy5SOmK6mzoOkHoVNWB/ChQz2inouNhtH0c",
	"H4QagOApcjd01/F4G/YGuvT0x0NB1EX9wbtjRIFZTexfDz5qIr6kZRxKIbHg8ybyuF788yb52PdN5BlQ",
	"nXD3Ok4xRdLWiTnoMelyPK4YVRCP+EyiejJdvzvdLlfChr6TdPrmzikk6QnNERviTgSZbdiW7RoJtBF3",
	"eqONzHj0Sp5l1Ez24ralqvESnr5FskNICt+LkZ87c1F2Sk2DDotwWenDe7Q1llJ6hup4BiPuMxu/vvE1",
	"nk4jDiLXbl/lSRg5bb5rrbGhWhclfqeKRjkGP0CdlkN1lID3T+mbZc/UsqkbLbV5nYiYCPZm5Udn6QOW",
	"0gfV3JL6BlF+aKjkFKzSguP5+XfNd02qPaj3lwI0Jz6hO1J/yzpW7EIUmsUv0uyxC2Hz8fLs8v8EAAD/",
	"/zSqw+xtWAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
